### ISSUE TITLE
Most of the Loggerhead option panes are blank

### ISSUE THREAD

**Issue by Unclevinny** [dratr/loggerhead#4]
In game, with Loggerhead installed, hit Escape -> Addons -> Loggerhead -> Party

I would expect to see options here for when log files will be stored. Instead, it's blank. Same with PvP, Raid, Scenarios, etc. 

![image](https://user-images.githubusercontent.com/879631/229940778-b0f234b1-8baa-4516-b151-faaf72b99d4c.png)

What are these panes for? Is there another addon I should install to enable them?

**Comment by kitsunekyo** [comment]
yeah this is a bit weird UX and should definitely be improved. but its working as "intended".
once you enter a dungeon or new zone, the addon will show a popup asking whether you want logging enabled for this instance. once you have done that, the instance will show up in this list.

you can try it by entering a dungeon alone.

**Comment by dratr** [comment]
As @kitsunekyo explained, what you are seeing is the intended behavior;  when you enter a dungeon on a specific difficulty setting for the first time, you are prompted to log or not (subject to some of the global options/filters) and the options list is populated with your response so that you can adjust it later if you have changed your disposition on logging that particular dungeon/difficulty.   The reason for this is two-fold:  it keeps the settings values small since it holds only preferences for content you enter/run and, more importantly, it prevents the addon from having to encompass a list of instances/dungeons/raids/etc in the game as the game does not provide a way for addons to easily query all such locations to build an exhaustive options list.
The addon, long long ago, used to pre-populate the options with all such dungeons by exhaustively listing them out, but this was growing to a very very large list and required a new version of the addon anytime new ingame content was added.  The current behavior lets the addon build the list dynamically without needing to be aware of new locations ahead of time.

That said, happy to accept ideas and/or merge requests for UI/UX improvements to make this clearer!

**Comment by kitsunekyo** [comment]
if i dont forget, i can make a pr with a short empty message in the settings saying something like "on entering a dungeon the addon will ask you whether you want to enable logging for this specific dungeon/difficulty combination. it will then show up here."
